version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports:
      - 8000:8000
    depends_on:
      - db
    networks:
      - dc_network
  db:
    image: mysql:latest
    restart: always
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: mysecretpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    env_file:
      - ./.env
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - dc_network

volumes:
  db_data:

networks:
  dc_network: