name: API Unit Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]
    # env:
    #   STATIC_ACCESS_KEY_ID: ${{ secrets.STATIC_ACCESS_KEY_ID }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with Black
        uses: rickstaa/action-black@v1
        with:
          black_args: ". --check"
      
      - name: Build App
        run: |
          cp .env.example .env
          make build
        
      - name: Run App
        run: |
          make run
          sleep 30
      
      # - name: build and Run App
      #   run: |
      #     cp .env.example .env
      #     make build-and-run
      #     sleep 30
      
      - name: Test app with Curl
        run: |
          curl http://127.0.0.1:8000/api/v1/brands/list
      
      - name: Run Pytest
        run: |
          pytest tests/

      - name: Destroy App
        run: |
          make destroy